version: '3'

services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./html:/var/www/html/
      - ./conf:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ./html:/var/www/html/
networks:
  internal:
    driver: bridge

